### ISSUE TITLE
No signal named `item_selected` in CtrlInventoryGrid

### ISSUE THREAD

**Issue by kingthrillgore** [peter-kish/gloot#132]
I noticed when working a project in Godot 4, there's no signal for the documented `item_selected` nor is there any such functionality for CtrlInventoryGrid or CtrlInventoryGridEx. If this is planned for a future update or has been discontinued, it would be nice to know what to use in the meantime when a grid item is deselected.

**Comment by peter-kish** [comment]
Hmm, you're right, the documentation for `CtrlInventoryGrid` is out of date.
Instead of `item_selected` there's the `selection_changed` signal which is triggered when an item is selected/deselected. There is also the `get_selected_inventory_item` function which returns the currently selected item.

I'll update the documentation in the next release.

**Comment by kingthrillgore** [comment]
I don't want to add any more to this issue but since we're here, what about programmatically removing the selection from the inventory? Its not documented, nor does it appear to be supported.

**Comment by peter-kish** [comment]
```gdscript
```

**Comment by peter-kish** [comment]
`CtrlInventoryGrid` documentation has been updated (b786c88c4008bf2ab3d2363b28131fdbb31c3b1c)
