### ISSUE TITLE
Item image will take up maximum height and width of image when used in a CtrlItemSlotEx

### ISSUE THREAD

**Issue by kingthrillgore** [peter-kish/gloot#140]
[This video demonstrates the issue more clearly](https://www.youtube.com/watch?v=eoD-t77pwqE). 

I'm not sure if this is a deeper bug with GLoot or simply my misuse of the library, but this bug has been problematic with inventory. I have a `CtrlItemSlotEx` connected to the same inventory as a larger inventory grid (seen in the grid to the right) and dragging into these slots cause the image used for the inventory item to be exploded to its full size, instead of being scaled down to a height of 80px, which is set as custom minimum height. Similarly, the parent `HBoxContainer` has a size of 80px high.

It is worth pointing out once moved outside these slots, it takes back its original size from the inventory grid. So the resize occurs when I change to these `CtrlItemSlotEx` slots.

The scene hierarchy is as follows, and mostly follows the `inventory_grid_transfer` demo from the GLoot example. I did try switching out the `CtrlItemSlotEx` with just an `CtrlItemSlot` and got not change in results.

![image](https://github.com/peter-kish/gloot/assets/216171/91e7f004-d8ce-450f-a46d-533ee1591268)

And while this is a personal project, if you need to inspect it to better track the bug, reach out and I can grant you access to the repo. These changes are based on the [2.3.8](https://github.com/peter-kish/gloot/milestone/6) release.

**Comment by peter-kish** [comment]
This behavior is intentional, even though I'm still unsure if it's the best way to handle various item image sizes.

The way it's currently implemented, item slots display item images in their original size multiplied with the `CtrlItemSlot.icon_scaling` property, while grid inventories scale them according to their field dimensions.

Setting the `custom_minimum_size` of a control does not set its size, it only guarantees that the control won't be smaller than that. Setting the size of a container also does not guarantee that all its children will be resized. You can put together a very simple scene with only an `HBoxContainer` containing a `TextureRect` and play around with sizes to see how Godot handles them.

But when it comes to your problem, I see two solutions:
1. Import resized item images. This might not be a viable solution if you still need the full resolution image to be displayed in some other UI components.
2. Calculate the `icon_scaling` property of the `CtrlItemSlot` dynamically - for example every time the mouse hovers over an inventory item (can be done using the `CtrlInventoryGrid.item_mouse_entered` signal) or every time an item is selected (`CtrlInventoryGrid.selection_changed` signal). E.g.:
```gdscript
func _on_selection_changed(item: InventoryItem) -> void:
    const desired_size = Vector2(80, 80)
    ctrl_item_slot.icon_scaling = desired_size / inventory_grid.get_item_size(item)
```

Ideally, there would be a signal that is emitted when a drag&drop operation starts, but that is still not implemented.

**Comment by kingthrillgore** [comment]
I think the approach of using a signal is the most approachable from my perspective, since I need to resize graphics based on screen real estate. While I wait for the signal support to be added, I will just use resized images for now.

**Comment by peter-kish** [comment]
This problem actually has a lot in common with https://github.com/peter-kish/gloot/issues/154, which has been implemented in https://github.com/peter-kish/gloot/commit/ecaf16ee0b3ed648dfd4c851e07861bc1de6f274.
