### ISSUE TITLE
Multi-select items in CtrlInventoryStacked

### ISSUE THREAD

**Issue by snipercup** [peter-kish/gloot#148]
I love your inventory system. It saves so much work on development time.

I saw in https://github.com/peter-kish/gloot/issues/110 that multi-selection is not yet supported. Will this be added in the future? Right now we would have to select an item and then click the transfer button for each of the items we want to transfer.

**Comment by snipercup** [comment]
Actually, never mind. I see now we're supposed to make our own UI and the one provided is for testing purposes. At least I got to tell you I really appreciate your work

**Comment by peter-kish** [comment]
Reopening this one as a reminder to implement this at some point.

> I see now we're supposed to make our own UI and the one provided is for testing purposes.

Yeah, that was the initial idea. But since a lot of people are making heavy use of the provided UI controls, at some point I decided to flesh them out and make them more useful. That, of course, still doesn't stop anyone from creating their own UI based on the core functionality of the addon.

> At least I got to tell you I really appreciate your work

Thanks!

**Comment by peter-kish** [comment]
Multi select mode for `CtrlInventory`, `CtrlInventoryStacked`, `CtrlInventoryGrid` and `CtrlInventoryGridEx` is implemented in [v2.4.6](https://github.com/peter-kish/gloot/releases/tag/v2.4.6) (holding down CTRL should allow you to select multiple items).
