### ISSUE TITLE
Option to disable alphabetical order on JSON strings

### ISSUE THREAD

**Issue by Mawkey** [peter-kish/gloot#165]
Hello! Amazing project and great contribution to Godot!
I have a feature request and it's not that important but it's a slight annoyance to me.

When you edit JSON using "edit protoset" button in the inspector, it forces your JSON properties to be in alphabetical order.
A setting in project or editor settings to disable that would be very nice.

You can bypass this issue by just editing the strings directly of course.

**Comment by peter-kish** [comment]
Implemented in caa6b4f5eb5685ee22fa89c0f677fbaa3b3ea660.
Turned out to be pretty straight-forward. While the JSON standard defines objects as "unordered collection of zero or more name/value pairs", the [JSON.stringify](https://docs.godotengine.org/en/stable/classes/class_json.html#class-json-method-stringify) function in Godot has an argument to enable/disable key sorting.
