### ISSUE TITLE
doesn't work in export

### ISSUE THREAD

**Issue by dukeman74** [peter-kish/gloot#188]
an exported project will break because gloot_undo_redo.gd uses EditorUndoRedoManager, which is not available in an exported project.  not including gloot_undo_redo.gd in the project also doesn't work because all the inventories preload it.

can be worked around by replacing those preloads with a load every time it actually gets used, but that seems ugly

**Comment by peter-kish** [comment]
Should be fixed now in c085f9323c91792f985223c0b25f172cbfebcb0e. Turned out it was enough to only remove `EditorUndoRedoManager` from `gloot_undo_redo.gd` on line 7.
It's probably a better idea to not include anything from `addons/gloot/editor` in the exports, but this will be enough for a quick fix.
